import React, { useState, useEffect } from 'react';

interface ScheduleDisplayProps {
  schedule: string;
  prompt: string;
  isLoading: boolean;
  error: string;
  onRegenerate: () => void;
  onReset: () => void;
}

interface Task {
  id: number;
  content: string;
  completed: boolean;
}

const ScheduleDisplay: React.FC<ScheduleDisplayProps> = ({
  schedule,
  prompt,
  isLoading,
  error,
  onRegenerate,
  onReset,
}) => {
  const [tasks, setTasks] = useState<Task[]>([]);
  const [completedCount, setCompletedCount] = useState(0);
  const [showPrompt, setShowPrompt] = useState(false);

  useEffect(() => {
    if (schedule) {
      parseSchedule(schedule);
    }
  }, [schedule]);

  useEffect(() => {
    setCompletedCount(tasks.filter(t => t.completed).length);
  }, [tasks]);

  const parseSchedule = (scheduleText: string) => {
    const lines = scheduleText.split('\n');
    const parsedTasks: Task[] = [];
    let taskId = 0;

    lines.forEach(line => {
      if (line.includes('[ ]')) {
        taskId++;
        const taskContent = line
          .replace(/^\*\*\s*/, '')
          .replace(/\[ \]\s*/, '')
          .replace(/\*\*/g, '');
        parsedTasks.push({
          id: taskId,
          content: taskContent.trim(),
          completed: false,
        });
      }
    });

    setTasks(parsedTasks);
  };

  const toggleTask = (taskId: number) => {
    setTasks(prevTasks =>
      prevTasks.map(task =>
        task.id === taskId ? { ...task, completed: !task.completed } : task
      )
    );
  };

  const renderScheduleHTML = () => {
    const lines = schedule.split('\n');
    const elements: React.ReactElement[] = [];
    let taskIndex = 0;

    lines.forEach((line, index) => {
      line = line.trim();

      if (!line) {
        elements.push(<br key={`br-${index}`} />);
        return;
      }

      if (line.startsWith('##')) {
        const headerText = line.replace(/^##\s*/, '').replace(/\*\*/g, '');
        elements.push(
          <h2 key={`header-${index}`} className="schedule-header">
            {headerText}
          </h2>
        );
        return;
      }

      if (line.match(/^\*\*[^:]+:\*\*$/)) {
        const sectionText = line.replace(/\*\*/g, '');
        elements.push(
          <h3 key={`section-${index}`} className="schedule-section">
            {sectionText}
          </h3>
        );
        return;
      }

      if (line.includes('[ ]')) {
        const currentTask = tasks[taskIndex];
        if (currentTask) {
          elements.push(
            <div key={`task-${currentTask.id}`} className="task-item">
              <label className="task-label">
                <input
                  type="checkbox"
                  className="task-checkbox"
                  checked={currentTask.completed}
                  onChange={() => toggleTask(currentTask.id)}
                />
                <span className={`task-text ${currentTask.completed ? 'completed' : ''}`}>
                  {currentTask.content}
                </span>
              </label>
            </div>
          );
          taskIndex++;
        }
        return;
      }

      if (line.startsWith('**') && line.endsWith('**')) {
        const noteText = line.replace(/\*\*/g, '');
        elements.push(
          <p key={`note-${index}`} className="schedule-note">
            <strong>{noteText}</strong>
          </p>
        );
        return;
      }

      if (line.startsWith('*') || line.startsWith('-')) {
        const bulletText = line.replace(/^[*-]\s*/, '');
        elements.push(
          <p key={`bullet-${index}`} className="schedule-bullet">
            • {bulletText}
          </p>
        );
        return;
      }

      if (line.length > 0) {
        elements.push(
          <p key={`text-${index}`} className="schedule-text">
            {line}
          </p>
        );
      }
    });

    return elements;
  };

  const progressPercentage = tasks.length > 0
    ? Math.round((completedCount / tasks.length) * 100)
    : 0;

  return (
    <div className="screen active">
      <h2>✨ Your Personalized Schedule</h2>
      <p>Generated by AI based on your preferences:</p>

      {isLoading && (
        <div className="loading">
          <div className="spinner"></div>
          <p>Generating your personalized schedule...</p>
        </div>
      )}

      {error && (
        <div className="error">
          <p>{error}</p>
        </div>
      )}

      {schedule && !isLoading && (
        <div className="schedule-output">
          {tasks.length > 0 && (
            <div className="schedule-progress">
              <div className="progress-bar">
                <div 
                  className="progress-fill" 
                  style={{ width: `${progressPercentage}%` }}
                />
              </div>
              <div className="progress-text">
                {completedCount} of {tasks.length} tasks completed ({progressPercentage}%)
              </div>
            </div>
          )}
          {renderScheduleHTML()}
        </div>
      )}

      {prompt && !isLoading && (
        <div className="prompt-section">
          <button
            type="button"
            className="btn btn-secondary"
            onClick={() => setShowPrompt(!showPrompt)}
            style={{ marginTop: '20px', width: '100%' }}
          >
            {showPrompt ? '▼ Hide AI Prompt' : '▶ View AI Prompt'}
          </button>
          {showPrompt && (
            <div className="prompt-display" style={{
              marginTop: '10px',
              padding: '15px',
              backgroundColor: '#f5f5f5',
              borderRadius: '5px',
              whiteSpace: 'pre-wrap',
              fontFamily: 'monospace',
              fontSize: '12px',
              maxHeight: '400px',
              overflowY: 'auto',
              border: '1px solid #ddd'
            }}>
              {prompt}
            </div>
          )}
        </div>
      )}

      <div className="navigation">
        <button type="button" className="btn btn-secondary" onClick={onReset}>
          ← Start Over
        </button>
        {schedule && (
          <button type="button" className="btn" onClick={onRegenerate}>
            🔄 Generate New
          </button>
        )}
      </div>
    </div>
  );
};

export default ScheduleDisplay;